[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"

[build.environment]
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
